### ISSUE TITLE
Incorrectly throwing error if line to slice is a valid LineString

### ISSUE THREAD

**Issue by nevi-me** [turf-junkyard/turf-line-slice#5]
The code on https://github.com/Turfjs/turf-line-slice/blob/master/index.js#L61 is:

``` javascript
  if (line.type === 'Feature') {
    coords = line.geometry.coordinates;
  } else if (line.type === 'LineString') {
    coords = line.geometry.coordinates;
  } else {
    throw new Error('input must be a LineString Feature or Geometry');
  }
```

A LineString won't have a geometry, so the error gets thrown. I'll submit a PR for this

**Comment by nevi-me** [comment]
I see that we missed this because we use `point` and `linestring`, which return features with those objects embedded as features. I prefer using the `Point` or `LineString` without embedding them in a feature, so that's how I picked up the issue. 

I'll try also check for points, after patching the above I am still getting errors elsewhere.

**Comment by nevi-me** [comment]
I held back on this because I noticed that turf in general seems to prefer using `Feature`, where some modules outright don't work with just geometries. Any thoughts @morganherlocker? Either way, we'd still need to fix this issue, by either rejecting `LineString` completely, or fixing the `line.geometry.coordinates` part.

**Comment by morganherlocker** [comment]
We used to aim for supporting both Geometries and Features whenever possible but it was too confusing. Turf uses Features for everything now.
